### ISSUE TITLE
[1.21] Some enchantment issues with tools and armor

### ISSUE THREAD

**Issue by kwpugh** [XxRexRaptorxX/ExtraGems#2]
I'm guessing you are missing some items listed in the new `enchantable` tags.

![Screenshot 2024-07-24 at 2 35 16 PM](https://github.com/user-attachments/assets/1b6806c0-37bd-485b-bcaa-dbfbe8f70610)
![Screenshot 2024-07-24 at 2 35 31 PM](https://github.com/user-attachments/assets/6848e1d6-0b4a-4c7d-8a4d-9bf886e93862)

**Comment by XxRexRaptorxX** [comment]
Thanks for your hint, i will fix this in the next version!:)
